# Generated by Django 5.2.5 on 2025-10-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_view_drafts', 'Может смотреть черновики')]},
        ),
    ]
